public enum Type {
	OPAREN, CPAREN,
	OCURLY, CCURLY,
	OBRACK, CBRACK,
	PLUS, MINUS, TIMES, DIV, MOD,
	LT, LTE, NEQ, EQ, GTE, GT,
	ASSIGN, DOT,
	AND, OR, NOT,
	TRUE, FALSE,
	IF, ELSE, WHILE,
	VAR, DEFINE, CLASS, EXTENDS, RETURN,
	COMMA, SEMICOLON,
	INTEGER,
	EOF,
	UNKNOWN
}

